### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by aremazeilles** [tecnalia-medical-robotics/tracebot_mockup#1]
Might be good placing a readme, with indication on how to install within a standard ROS noetic environment, or how to use the docker image directly (even using the rocker tools)

You don´t use anymore rosinstall files ? I see this file `noetic.repos` , is it a new way of defining external repo dependencies?

There is no Dockerfile neither. You go through another mechanism to create your docker image?
What would be  great would be to get the docker image updated from the CI.  I do it in Eurobench, triggered by the creation of a tagged version. We can discuss this later on.

I hope that providing this initial material, we could progressively add more realistic element in the environment.

**Comment by miguelprada** [comment]
Sure. Done!
