### ISSUE TITLE
rviz crashes with pre-built container 

### ISSUE THREAD

**Issue by dornik** [tecnalia-medical-robotics/tracebot_mockup#5]
When running `rocker --x11 -- miguelprada/tracebot_mockup:noetic roslaunch tracebot_mockup_description view_tracebot_mockup.launch`, the `joint_state_publisher_gui`opens but rviz crashes at startup.

I've tested on Ubuntu 16.04 with docker 19.03.14, rocker 0.2.3 and nvidia-455 and on 20.04 with docker 20.10.7, same rocker version and nvidia-460. The latter has a clean (nvidia-)docker installation.

The rocker examples (rviz and gazebo) are working. I've also been able to get `tracebot_mockup` to work by manually installing everything, starting from the ROS Melodic base image and then following your instructions. So I assume this is rather an issue with the container.

If someone is able to reproduce this error, please verify. If it is working for you, please check if there are any additional flags or settings missing from the documentation.

PS: The rocker documentation misses the information that `python3-distutils` needs to be installed beforehand, if you run into any trouble there.

**Comment by miguelprada** [comment]
In order to properly use your NVidia graphics card, you also need to pass `--nvidia` flag to rocker. Can you try with:

```bash
rocker --x11 --nvidia -- miguelprada/tracebot_mockup:noetic roslaunch tracebot_mockup_description view_tracebot_mockup.launch
```

Also, be sure to refresh the docker image with either an explicit `docker pull miguelprada/tracebot_mockup:noetic` or by adding the `--pull` flag to your `rocker` command. I hadn't yet updated the previous image after a recent incident where the GPG signing keys for the ROS package repositories was expired. Without doing so, any `apt update` command would fail, and this happens as part of the setup `rocker` does when given the `--nvidia` flag. The currently available image should work just fine.

Regarding the `rocker` dependency, how did you go about installing it? I just tested using _pip_, both from source and from PyPI packages, and I had no problem at all.

**Comment by jibweb** [comment]
For me, if I run `rocker --pull --x11 --nvidia -- miguelprada/tracebot_mockup:noetic` I get:

```
output:  standard_init_linux.go:211: exec user process caused "permission denied"

/tmp/detect_os failed:
> standard_init_linux.go:211: exec user process caused "permission denied"
WARNING unable to detect os for base image 'miguelprada/tracebot_mockup:noetic', maybe the base image does not exist

```

and if I run `rocker --pull --x11 -- miguelprada/tracebot_mockup:noetic` I can get a prompt, but running `roslaunch tracebot_mockup_description view_tracebot_mockup.launch` inside the container gives me 
```
[ERROR] [1624615021.429683022]: Unable to create the rendering window after 100 tries.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[rviz-4] process has died [pid 57, exit code -6, cmd /opt/ros/noetic/lib/rviz/rviz -d /opt/ros/tracebot_mockup-noetic/share/tracebot_mockup_description/config/tracebot_mockup.rviz __name:=rviz __log:=/root/.ros/log/af36db76-d59b-11eb-85a7-0242ac110002/rviz-4.log].
log file: /root/.ros/log/af36db76-d59b-11eb-85a7-0242ac110002/rviz-4*.log
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

```

**Comment by miguelprada** [comment]
I think you're running into an issue with the NVidia support in _rocker_ (affecting images with a default non-root user) for which we recently got a [patch](https://github.com/osrf/rocker/pull/150) merged into _main_. This patch is possibly not present in the released version of _rocker_ in PyPI. Can you try to install _rocker_ from source?

If this is problematic for you let me know and I can try to create a version of the image where _root_ is the default user, which should also solve the problem.

**Comment by jibweb** [comment]
Installing rocker with `pip install git+https://github.com/osrf/rocker.git` worked for me

**Comment by miguelprada** [comment]
I'll go ahead and merge #6 then.
